image: node:16.13.2

definitions:
  steps:
    - step: &release
        name: Release
        script:
          - yarn release

pipelines:
  branches:
    alpha:
      - step:
          <<: *release
          name: Release (alpha)
    beta:
      - step:
          <<: *release
          name: Release (beta)
    master:
      - step: *release
