image: node:14.15.1

pipelines:
  tags:
    v*:
      - step: &publish-library
          name: Publish library
          script:
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
